# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'

stages:
- stage: 'Build'
  jobs:
  - job: 'Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        publishWebProjects: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'beer-xchange-web'
        publishLocation: 'Container'
      displayName: 'publish build artifacts'

- stage: 'DeployDev'
  jobs:
  - deployment: DeployJob
    displayName: Deploy Job
    pool:
      vmImage: 'Ubuntu-latest'
    environment: 'beer-xchange dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'beer-xchange-web'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'beer-xchange-dev'
              appType: 'webApp'
              WebAppName: 'xpirit-beer-xchange-dev'
              packageForLinux: '$(System.ArtifactsDirectory)/beer-xchange-web/*.zip'
            displayName: 'Deploy dev web app'

- stage: 'DeployProd'
  jobs:
  - deployment: DeployJob
    displayName: Deploy Job
    pool:
      vmImage: 'Ubuntu-latest'
    environment: 'beer-xchange production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'beer-xchange-web'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'beer-xchange-prod'
              appType: 'webApp'
              WebAppName: 'xpirit-beer-xchange'
              packageForLinux: '$(System.ArtifactsDirectory)/beer-xchange-web/*.zip'
            displayName: 'Deploy production web app'




